In [3]:
import numpy as np

In [4]:
# np.short(#) creates a 16 bit signed int with a max value of
# "half of 2^16-1" to account for positive and negative integers
myShort = np.short(15)
print(myShort)
print(type(myShort))

15
<class 'numpy.int16'>


In [5]:
# np.array([#,#,#,#]) creates a vector which is basically a list
myVect = np.array([1,2,3,4])
print(myVect)
print(type(myVect))
print(type(myVect[0]))


[1 2 3 4]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [6]:
# np.arange(#1,#2,#3) creates a vector of numbers from #1 to #2 counting by #3
myVect = np.arange(1,10,2)
print(myVect)
print(type(myVect))
print(type(myVect[0]))

[1 3 5 7 9]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [7]:
# np.int16([#,#,#,#]) creates a vector of 16 bit signed integers
myVect = np.int16([1,2,3,4])
print(myVect)
print(type(myVect))
print(type(myVect[0]))

[1 2 3 4]
<class 'numpy.ndarray'>
<class 'numpy.int16'>


In [8]:
# Easily add to an entire vector
myVect = np.array([1,2,3,4])
print(myVect + 50)
print(type(myVect))
print(type(myVect[0]))

[51 52 53 54]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [9]:
myVect = np.ones(4)
print(myVect)
print(type(myVect))
print(type(myVect[0]))

[1. 1. 1. 1.]
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [10]:
myVect = np.ones((4,2))
print(myVect)
print(type(myVect))
print(type(myVect[0]))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
# Easily add to an entire array
np.ones((4,2)) + 50

array([[51., 51.],
       [51., 51.],
       [51., 51.],
       [51., 51.]])

In [12]:
# Compare each value in 2 equal Vectors
a = np.array([1,2,3,4])
b = np.array([1,5,3,4])
print(a == b)
print(type(a == b))
print(type((a == b)[0]))
print(a < b)

[ True False  True  True]
<class 'numpy.ndarray'>
<class 'numpy.bool'>
[False  True False False]


In [13]:
# Logical operators

a = np.array([True, False, True, False])
b = np.array([True, True, False, False])

## Logical or compares each element.  Any True makes this True
print(np.logical_or(a, b))

## Logical and compares each element.  Any False makes this false
print(np.logical_and(a, b))

## Logical not flips each bool to its opposite.
print(np.logical_not(a))

## Logical xor (exclusive or) compares each element.  Any True makes this Truexor only returns true if one element is True and the other is False
print(np.logical_xor(a, b))

[ True  True  True False]
[ True False False False]
[False  True False  True]
[False  True  True False]


In [14]:
# Multiplying vectors
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a * b)

[ 1  4  9 16]


In [15]:
# Multiplying vectors
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(np.multiply(a,b))

[ 1  4  9 16]


In [ ]:
# Dot product of 2 arrays.  Multiple each element place by place and add them together
# a · b = (1*1) + (2*2) + (3*3) + (4*4) = 1 + 4 + 9 + 16 = 30
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

a.dot(b)

np.int64(30)

In [17]:
# make a matrix a.k.a. multi dimensional array

myMatrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(myMatrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
myMatrix2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(myMatrix2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
# Multiply 2 matrixes//arrays
print(myMatrix * myMatrix2)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [20]:
# Calculate a vector's Square of Magnitude

v = np.array([3, 4])
square_of_magnitude = v.dot(v) # = 3^2 + 4^2
print(f"The vector is: {v}")
print("The square of its magnitude is: 3^2 + 4^2")
print(f"The square of its magnitude is: {square_of_magnitude}")

The vector is: [3 4]
The square of its magnitude is: 3^2 + 4^2
The square of its magnitude is: 25


# Creating Matrices

### Data-type: Array (np.array(...))

In [21]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [22]:
# multiply 2 numpy array/matrices
# must be the same shape
np.array([[1,2,3],[4,5,6]])
print(a)
b = np.array([[1,2,3],[4,5,6]])
c = a*b
print(c)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]


### Data-type: Matrix (np.asmatrix(...))

*   (2-dimensional matrices only. Specialized features)

In [23]:
# enables specialized matrix functions and processing
a = np.asmatrix([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.matrix'>


In [38]:
# multiplying 2 matrices doesnt work like multiplying 2 arrays
a = np.asmatrix([[1,2,3],[4,5,6]])
b = np.asmatrix([[1,2,3],[4,5,6]])
#c = a*b     <<----- Causes an error because the matrices are not compatible for dot product multiplication

# matrix (dot product) multiplication requires the number of columns in the first matrix to equal the number of rows in the second matrix
a = np.asmatrix([[1,2,3],[4,5,6]])
b = np.asmatrix([[1,2,3],[3,4,5],[5,6,7]])
c = a*b 
print(c)

# For elementwise multiplication, multiply 2 numpy arrays
a = np.asmatrix([[1,2,3],[4,5,6]])
b = np.asmatrix([[1,2,3],[4,5,6]])
c = np.asarray(a) * np.asarray(b)
print(c)

# Or for elementwise multiplication, use the numpy multiply function
c = np.multiply(a, b)
print(c)



[[22 28 34]
 [49 64 79]]
[[ 1  4  9]
 [16 25 36]]
[[ 1  4  9]
 [16 25 36]]


In [ ]:
# convert an array to a matrix and vice versa

a = np.array([[1,2,3],[4,5,6]])
print(type(a))
print(a)

b = np.asmatrix(a)
print(type(b))
print(b)

c = np.asarray(b)
print(type(c))
print(c)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [ ]:
# Dot Product of 2 matrices. Multiple the row of a by the column of b
# a · b = a₁*b₁ + a₂*b₂ + ... + aₙ*bₙ
# a * b = (1*4) + (2*5) + (3*6) = 4 + 10 + 18 = 32

a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[1,2,3],
              [3,4,5],
              [5,6,7]])

print(a.dot(b))

[[22 28 34]
 [49 64 79]]


In [ ]:
# Reshaping an vector/array into a matrix

print('Array')
changeIt = np.array([1,2,3,4,5,6,7,8])
print(changeIt)

print('Reshape to 2x4 matrix')
changeIt = changeIt.reshape(2,4)
print(changeIt)

print('Reshape to 2x2x2 matrix')
changeIt = changeIt.reshape(2,2,2)
print(changeIt)

Array
[1 2 3 4 5 6 7 8]
Reshape to 2x4 matrix
[[1 2 3 4]
 [5 6 7 8]]
Reshape to 2x2x2 matrix
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
